name: picaster
version: 'dev'
summary: Podcast recording and streaming application
description: |
  PiCaster is a podcast recording and streaming application,
  easy to use for beginners, but with enough functionaliy
  to suit the needs of intermediate or experienced podcasters.

grade: devel
confinement: devmode

apps:
  picaster:
    command: desktop-launch alsa-launch $SNAP/bin/picaster
    desktop: share/applications/picaster.desktop
    plugs: 
      - pulseaudio
      - home
      - network
      - x11
      - desktop

parts:
  alsa:
    after:
      - alsa-plugins
      - alsa-lib
  alsa-plugins:
    after:
      - alsa-lib
  picaster:
    plugin: autotools
    source: https://github.com/frenchguych/alsa-snap-test.git
    source-branch: master
    after: 
      - desktop-gtk3
      - alsa
    build-packages:
      - build-essential
      - valac
      - libgtk-3-dev
    stage:
      - -usr/share/alsa
