name: picaster
version: 'dev'
summary: Podcast recording and streaming application
description: |
  PiCaster is a podcast recording and streaming application,
  easy to use for beginners, but with enough functionaliy
  to suit the needs of intermediate or experienced podcasters.

grade: devel
confinement: devmode

apps:
  picaster:
    command: desktop-launch alsa-launch $SNAP/bin/picaster
    desktop: share/applications/picaster.desktop
#    environment:
#      ALSA_CONFIG_PATH: /snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
    plugs: 
#      - alsa
      - pulseaudio
      - home
      - network
      - x11
      - desktop
#    plugs: [alsa,pulseaudio,home,gsettings,x11,desktop,network,network-bind,removable-media]

parts:
  alsa:
    after:
      - alsa-plugins
      - alsa-lib
  alsa-plugins:
    after:
      - alsa-lib
#  alsa-lib:
#    plugin: autotools
#    source: ftp://ftp.alsa-project.org/pub/lib/alsa-lib-1.1.6.tar.bz2
#    configflags:
#      - --prefix=/usr
#      - --sysconfdir=/etc
#      - --libexec=/usr/lib
#      - --libdir=/usr/lib
#      - --localstatedir=/var
#      - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
#      - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
#      - --disable-static
#    stage:
#      - usr/include
#      - usr/lib
#    prime:
#      - -usr/bin
#      - -usr/include
#      - -usr/lib/pkgconfig
#      - -usr/share/alsa/alsa.conf
#      - -usr/share/alsa/pcm
#      - -usr/share/alsa/topology/broadwell
  picaster:
    plugin: autotools
    source: /mnt/bulbizarre/PiCaster/src
    after: 
      - desktop-gtk3
      - alsa
#      - alsa-lib
    build-packages:
      - build-essential
      - valac
      - libgtk-3-dev
    stage:
      - -usr/share/alsa
