name: alsa-snap-test
version: 'dev'
summary: alsa snap test
description: |
  alsa snap test

grade: devel
confinement: devmode

apps:
  alsa-snap-test:
    command: desktop-launch alsa-launch $SNAP/bin/alsa-snap-test
    plugs: 
      - alsa
      - pulseaudio
      - home
      - network
      - x11
      - desktop

parts:
  alsa:
    after:
      - alsa-plugins
      - alsa-lib
  alsa-plugins:
    after:
      - alsa-lib
  alsa-snap-test:
    plugin: autotools
    source: https://github.com/frenchguych/alsa-snap-test.git
    source-branch: master
    after: 
      - desktop-gtk3
      - alsa
    build-packages:
      - build-essential
      - valac
      - libgtk-3-dev
    stage:
      - -usr/share/alsa
